"""creat calo table

Revision ID: 4768b91c9e24
Revises: 5e4f9b9e4e43
Create Date: 2023-09-08 12:08:57.811756

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4768b91c9e24'
down_revision = '5e4f9b9e4e43'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
