"""creat calo table

Revision ID: 56939d841878
Revises: 4768b91c9e24
Create Date: 2023-09-08 12:09:51.500357

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56939d841878'
down_revision = '4768b91c9e24'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
