"""creat calo table

Revision ID: 5e4f9b9e4e43
Revises: dec41bc5b549
Create Date: 2023-09-08 11:46:14.199987

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5e4f9b9e4e43'
down_revision = 'dec41bc5b549'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calo',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('created_date', sa.Date(), server_default=sa.text('now()'), nullable=False),
    sa.Column('calo_in', sa.Float(), nullable=False),
    sa.Column('calo_out', sa.Float(), nullable=False),
    sa.Column('calo_diff', sa.Float(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('calo')
    # ### end Alembic commands ###
