"""creat calo table

Revision ID: 66623885ed6b
Revises: ef0177c4a493
Create Date: 2023-09-08 01:13:20.883136

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66623885ed6b'
down_revision = 'ef0177c4a493'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
