"""creat users table

Revision ID: c2242cd85547
Revises: 66623885ed6b
Create Date: 2023-09-08 11:39:04.739085

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c2242cd85547'
down_revision = '66623885ed6b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('calo_user_id_fkey', 'calo', type_='foreignkey')
    op.drop_column('calo', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('calo', sa.Column('user_id', postgresql.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key('calo_user_id_fkey', 'calo', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
