"""creat calo table

Revision ID: dec41bc5b549
Revises: c2242cd85547
Create Date: 2023-09-08 11:39:12.224412

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dec41bc5b549'
down_revision = 'c2242cd85547'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
